# -*- coding: utf-8 -*-
"""Health AI app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFq44yvkJvByB2lwXUT4T3hdywWhSEXB
"""

!pip install gradio transformers
!python HealthAI_Categorized.py

# HealthAI_Categorized.py

import gradio as gr
from transformers import pipeline

# Dummy function for symptom-to-disease
def identify_disease(symptoms):
    return "Based on your symptoms, you may be experiencing a viral infection. Please consult a doctor."

# Dummy function for disease-to-remedies
def get_remedy(disease):
    return "For " + disease + ", try home remedies like turmeric milk and steam inhalation."

# Chatbot pipeline
chatbot = pipeline("text-generation", model="microsoft/DialoGPT-medium")

def chat_with_ai(message):
    result = chatbot(message, max_length=100, do_sample=True)[0]['generated_text']
    return result

# Gradio Interface
with gr.Blocks() as health_ai:
    gr.Markdown("# 🩺 **Health AI – Intelligent Healthcare Assistant**")
    with gr.Tabs():
        with gr.TabItem("🧑‍⚕️ Symptoms Identifier"):
            symptom_input = gr.Textbox(label="Enter Symptoms", placeholder="e.g., fever, cough, body pain")
            symptom_output = gr.Textbox(label="Possible Disease")
            gr.Button("Identify").click(identify_disease, inputs=symptom_input, outputs=symptom_output)

        with gr.TabItem("🌿 Home Remedies"):
            disease_input = gr.Textbox(label="Enter Disease", placeholder="e.g., cold, headache")
            remedy_output = gr.Textbox(label="Suggested Home Remedy")
            gr.Button("Get Remedy").click(get_remedy, inputs=disease_input, outputs=remedy_output)

        with gr.TabItem("💬 Chat Assistant"):
            user_input = gr.Textbox(label="Ask any health-related question")
            ai_output = gr.Textbox(label="Health AI Response")
            gr.Button("Ask AI").click(chat_with_ai, inputs=user_input, outputs=ai_output)
    gr.Markdown("Build by Bangaru Tejaswini as Internship Project on Health AI")

health_ai.launch()